#!/bin/bash
set -e

# Check if hook is enabled
if [[ "$(git config --get gitleaks.enable)" != "true" ]]; then
  echo "Skipping gitleaks (disabled via git config gitleaks.enable)."
  exit 0
fi

# Check if gitleaks is installed
if ! command -v gitleaks &> /dev/null; then
  echo "Gitleaks not found."
fi

# Run gitleaks
echo "Running gitleaks scan..."
gitleaks protect --staged --verbose --redact